apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: falco-sidekick-demo
spec:
  addonsConfig:
    dnsCacheConfig:
      enabled: false
    gcePersistentDiskCsiDriverConfig:
      enabled: false
    horizontalPodAutoscaling:
      disabled: false
    httpLoadBalancing:
      disabled: false
    networkPolicyConfig:
      disabled: false
  clusterAutoscaling:
    autoscalingProfile: BALANCED
    enabled: false
  databaseEncryption:
    state: DECRYPTED
  enableBinaryAuthorization: true
  enableShieldedNodes: true
  location: northamerica-northeast1-a
  loggingService: logging.googleapis.com/kubernetes
  initialNodeCount: 2
  masterAuth:
    clientCertificateConfig:
      issueClientCertificate: false
  monitoringService: monitoring.googleapis.com/kubernetes
  networkRef:
    name: falco-net
  subnetworkRef:
    name: falco-subnet
  networkPolicy:
    enabled: true
    provider: CALICO
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS_CONTAINERD
    machineType: e2-medium
    metadata:
      disable-legacy-endpoints: "true"
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/service.management.readonly
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/trace.append
    - https://www.googleapis.com/auth/devstorage.read_only
    preemptible: true
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    # workloadMetadataConfig:
    #   nodeMetadata: GKE_METADATA_SERVER
  podSecurityPolicyConfig:
    enabled: false
  releaseChannel:
    channel: REGULAR
---