apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    security: "falco"
  name: falco-sidekick
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: falco-alerts
  labels:
    security: "falco"
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: falco-sidekick
  pushConfig:
    pushEndpoint: https://pubsub-tutorial-w4gkhlavjq-nn.a.run.app
    oidcToken:
      serviceAccountEmail: cloud-run-pubsub-invoker@kubernetes-configs.iam.gserviceaccount.com