apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    zone: dev
  name: falco-subnet
spec:
  ipCidrRange: 10.3.0.0/16
  region: northamerica-northeast1
  description: kcc deployed subnet for k8s-cluster
  privateIpGoogleAccess: false
  networkRef:
    name: falco-net